# Generated by Django 3.0 on 2019-12-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191215_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='dementions',
            new_name='dimensions',
        ),
    ]
